### ISSUE TITLE
"E: 'python3-venv' has no installation candidate" while installing python3-venv package on target machine

### ISSUE THREAD

**Issue by harminderharrysingh** [tmurakam/kubespray-offline#1]
Hi @tmurakam 

After copying the 'outputs' directory to target-server, and performing all 5 steps, the following error appears while installing python3-venv package.
Could you please guide on what could be missed before this step?
Let me know if any more logs are required for your reference.

```
root@UERANSIM-2:~/outputs# apt-get install python3-venv --print-uris
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package python3-venv is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'python3-venv' has no installation candidate
```

**Comment by tmurakam** [comment]
Which OS are you using for preparation machine and target nodes?

**Comment by tmurakam** [comment]
Uh, you need to run `apt update` before apt install. I will fix README.

**Comment by tmurakam** [comment]
Fixed README.

**Comment by bjeyabalan** [comment]
Hi @tmurakam , 
Can you please let me know when the README says "cd [kubespray-dir]" , where exactly this directory is? what is the name of it? I see only outputs/ directory in the offline node. Please clarify.
