### ISSUE TITLE
Possible Typo in roles/offline-repo/default/main.yml

### ISSUE THREAD

**Issue by as9333** [tmurakam/kubespray-offline#12]
Hello,

I have used this support scripts to setup an offline kubernetes cluster with os: Redhat 8.6. After running the offline-repo.yml playbook, my target nodes are not getting updated with offline repo configurations. 

Checking the roles/offline-repo/default/main.yml , I can see the yum_repo is having the value: http://localhost:35000/rpms

By default the 35000 port is for Container registry and port 80 is for Rpm package. Will this be the reason for my issue

Thanks

**Comment by tmurakam** [comment]
Thanks, this is just a my mistake. I will fix this right away.

**Comment by tmurakam** [comment]
Fixed
