### ISSUE TITLE
./start-nginx.sh nginx mount /usr/share/nginx/html/rpm/local  no such file or not directory

### ISSUE THREAD

**Issue by Ghostwritten** [tmurakam/kubespray-offline#15]
![image](https://user-images.githubusercontent.com/19782612/230876419-3efb99d1-d034-44fe-9ba2-378ee869415c.png)

**Comment by tmurakam** [comment]
I think your offline.yml is misconfigured. The 'yum_repo' must have the path to 'rpms', not 'rpm'.
