### ISSUE TITLE
libselinux-python while running download-all.sh

### ISSUE THREAD

**Issue by Sillyon** [tmurakam/kubespray-offline#4]
I'm getting the following error while running download-all.sh:

`TASK [Generate files.list and images.list files from templates] **********************************************************************************************************************************************************`
`failed: [localhost] (item=files) => {"ansible_loop_var": "item", "changed": false, "checksum": "bcc95027282f789b2c0eadb4c30f25ce00a0a98d", "item": "files", "msg": "Aborting, target uses selinux but python bindings (libselinux-python) aren't installed!"}`
`failed: [localhost] (item=images) => {"ansible_loop_var": "item", "changed": false, "checksum": "a7b9d3fcfae6eff6f6f5355b069d19f53efb2816", "item": "images", "msg": "Aborting, target uses selinux but python bindings (libselinux-python) aren't installed!"}`

Then, I installed libselinux-python via yum (_libselinux-python-2.5-15.el7.x86_64_) but _download-all.sh_ is still throwing the same error.

Any suggestion?

OS INFO:
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

**Comment by Sillyon** [comment]
That addressed me to download-kubespray-files.sh actually. Any suggestion?

**Comment by tmurakam** [comment]
I think you need to install the package in venv, not yum.

Try this:
```bash
$ source ~/.venv/default/bin/activate
$ pip install selinux
```

Note: I don't test this script in SELinux enabled environment.

**Comment by tmurakam** [comment]
Oops, this is my mistake. I think you need to install libselinux-python3, not libselinux-python.

**Comment by Sillyon** [comment]
Resolved now, thanks!
