### ISSUE TITLE
"rootless containerd not running?" issue after running setup-container.sh

### ISSUE THREAD

**Issue by Sillyon** [tmurakam/kubespray-offline#5]
I can't access `containderd cli (nerdctl)` in my target node after I run `setup-container.sh`.
Here is the screenshot below:
![Screenshot_1](https://user-images.githubusercontent.com/30758522/169962860-bfb8d1bf-63df-4d45-b322-8d8948e3f284.png)

OS INFO (Azure Portal VM):
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

**Comment by tmurakam** [comment]
The nerdctl is installed in /usr/local/bin, so you need to use full path, or add /usr/local/bin to PATH environment variable.
Note: The sudo command does not inherit environment variable.
