### ISSUE TITLE
[CentOS 7] can not install ansible in target node

### ISSUE THREAD

**Issue by Sillyon** [tmurakam/kubespray-offline#6]
In my target node, while I am trying to install Ansible by running the `pip install -r requirements.txt` command, I'm getting the following `flit_core` and `pyparsing` errors:
![Screenshot_1](https://user-images.githubusercontent.com/30758522/170033226-4980183d-42bf-4a25-adaf-0be4969555b7.png)

The only solution for me is to copy the `.venv` directory from the downloader source machine and run the same command. Any solution?

**OS INFO (Azure Portal VM):**
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

**Comment by tmurakam** [comment]
Hmm.. It seems to be related to https://github.com/pyparsing/pyparsing/pull/360

**Comment by tmurakam** [comment]
Fixed.

**Comment by Sillyon** [comment]
With the new updates, I still can not install ansible on the target machine:
![MicrosoftTeams-image](https://user-images.githubusercontent.com/30758522/170939364-997347cf-f9b0-404e-b133-d80c20a5e0b3.png)
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/30758522/170939379-96f27e9a-8bbb-4e4b-a44d-33a3b3a301f4.png)

Python info:
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/30758522/170939753-d6034699-394b-41b2-873d-ed5254e3e9ef.png)

os info:
![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/30758522/170939829-69bfd64b-365e-4452-8ac3-bcc221b0b0f3.png)

**Comment by Sillyon** [comment]
Working fine.
Thanks for your interest!

**Comment by craftsman18** [comment]
@tmurakam Thank you so much for your works.. :)
