### ISSUE TITLE
need docker to run kubespray but new k8s using conatinerd

### ISSUE THREAD

**Issue by XDavidT** [tmurakam/kubespray-offline#8]
> Note: You must execute this process on same OS of k8s target nodes.
> 
> Before download offline files, check and edit configurations in config.sh.
> 
> If you don't have docker installed, run install-docker.sh to install Docker CE.

As far as I know - the new k8s version doesn't use docker anymore - hence why do we need to pre-install docker for offline installation?

**Comment by tmurakam** [comment]
No need to install docker-ce.

If you want to use containerd instead, run 'install-containerd.sh' to install containerd and nerdctl.
Then update config.sh to use nerdctl instead of docker.

**Comment by tmurakam** [comment]
Fixed README.
